-- MySQL Script generated by MySQL Workbench
-- jue 28 mar 2024 21:48:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema polygon_io
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema polygon_io
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `polygon_io` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `polygon_io` ;

-- -----------------------------------------------------
-- Table `polygon_io`.`day_aggs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `polygon_io`.`day_aggs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ticker` VARCHAR(10) NULL DEFAULT NULL,
  `volume` INT UNSIGNED NULL DEFAULT NULL,
  `open` DECIMAL(12,2) NULL DEFAULT NULL,
  `close` DECIMAL(12,2) NULL DEFAULT NULL,
  `high` DECIMAL(12,2) NULL DEFAULT NULL,
  `low` DECIMAL(12,2) NULL DEFAULT NULL,
  `window_start` DATETIME NULL DEFAULT NULL,
  `transactions` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
